name: Dispatch event
on:
  release:
    types: [released]
jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - uses: guilouro/multiple-repositories-dispatch@v1
      - with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          event_type: event_name
          repositories: |
            GabrielTiveron/Release_Receiver
          client_payload: '{"github": ${{ toJson(github) }}}'
