name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1.8.9
      with:
        artifacts: "curl ${{secrets.SONAR_URL}}"
        bodyFile: "README.md"
        token: ${{ secrets.GITHUB_TOKEN }}
