name: Releases

on: 
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set file
      id: filesetting
      run: timedatectl set-timezone America/Sao_Paulo && echo "::set-output name=metrics_report::REPO_NAME-$(date "+%Y.%m.%d-%H.%M.%S")"
    - name: Get metrics
      id: metrics
      run: curl "${{secrets.SONAR_URL}}" > ${{steps.filesetting.outputs.metrics_report}}.json
    - name: Get release version
      id: new_tag
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set artifact
      uses: ncipollo/release-action@v1.8.9
      with:
        tag: ${{steps.new_tag.outputs.new_tag}}
        artifacts: ${{steps.filesetting.outputs.metrics_report}}.json
        body: ${{steps.new_tag.outputs.changelog}}
        token: ${{ secrets.GITHUB_TOKEN }}
  receiver:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: Frontend
    steps:
      - name: blabla
        uses: guilouro/multiple-repositories-dispatch@v1.0.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          event_type: event_name
          repositories: |
            GabrielTiveron/Release_Receiver
          client_payload: '{"repo_name": "${{ env.REPO_NAME }}"}'
