name: Releases

on: 
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: samuca
      id: corno
      run: curl "${{secrets.SONAR_URL}}" > gay.json
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1.8.9
      with:
        artifacts: ${{steps.corno.outputs.gay.json}}
        token: ${{ secrets.GITHUB_TOKEN }}
